### ISSUE TITLE
Airmass and extra information from export-curves.py

### ISSUE THREAD

**Issue by aaegea** [vterron/lemon#101]
Hello,

I would like to know how to obtain (if possible) the following information from the differential photometry Lemon database (e.g., object-diff.LEMONdb): 

Airmass, XY position of the target in the detector, FWHM of the PSF of the target and background.

I need this info from each individual image to do the detrending of the light curves. I am using export-curves.py but this program only shows the values of “unix_time, magnitude, snr, merr_pos, merr_neg”.

Thanks!

Alba

**Comment by vterron** [comment]
Hi Alba,

> [...] XY position of the target in the detector [...] 

I would recommend using `export-curves.py` as the starting point and modify it to fit your needs. In particular, [`LEMONdB.get_star()`](https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/database.py#L987) will return both the x- and y-image coordinates of a star.

> Airmass [...]

This one is a little bit trickier: you'll need [`LEMONdB.get_image()`](https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/database.py#L942) to get the [`Image`](https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/database.py#L203) object that corresponds to a particular Unix time and photometric filter. In other words: for a given filter, you need to call this function for all the (Unix) times in which your object was observed, and then read the airmass from the `Image` object it returns.

> FWHM of the PSF of the target and background.

I don't think this is possible, sorry. This is not an measurement we take. [These are the fields](https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/qphot.py#L96) that IRAF's qphot returns.
