### ISSUE TITLE
Lemon on fedora

### ISSUE THREAD

**Issue by azim7091** [vterron/lemon#106]
Hi,

Is there a way to install Lemon on a fedora machine? I would be grateful for any help.

Thanks

**Comment by vterron** [comment]
I've never installed Lemon on Fedora, but it should be a matter of running the Fedora-equivalent commands of [the installation steps outlined here](https://lemon.readthedocs.io/en/stable/user/install.html). Please feel free to contribute a pull request to document the Fedora-specific installation instructions if you manage to do it successfully.

Alternatively, you may just opt for installing and running Lemon inside a Debian virtual machine. Personally that's what I'm currently doing (via VirtualBox + Vagrant) at home on my Arch Linux workstation.
