### ISSUE TITLE
NotImplementedError in multiprocessing.queues on Mac OS

### ISSUE THREAD

**Issue by mrkite92** [vterron/lemon#11]
Dear lemon gurus,

This is my first test of your package on my Mac under Mac OS 10.7.5, I got the following issue:

```
./lemon seeing ~/Desktop/sm00404/sm00404trr* ~/Desktop/sm00404lemon
>> Images will be saved to directory '/Users/marquett/Desktop/sm00404lemon'
>> 652 paths given as input, on which sources will be detected.
>> Running SExtractor on all the FITS images...
>> 0%[>                                                                        ]ERROR: NotImplementedError [multiprocessing.queues]
2014-05-05 14:46:12,329 - astropy - ERROR - NotImplementedError
Traceback (most recent call last):
  File "./lemon", line 98, in <module>
    module.main(args)
  File "/Users/marquett/Downloads/lemon-master/seeing.py", line 655, in main
    methods.show_progress(queue.qsize() / len(input_paths) * 100)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 143, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

It looks like something is missing in the multiprocessing. I use Python 2.7.6 through MacPorts.

Thanks for any hint,
Cheers,
Jean-Baptiste

**Comment by tvphan** [comment]
I run into the same error for Mac Yosemite 10.10.3.
Please advise how I can get this fix. Thanks.

**Comment by vterron** [comment]
Sure! It's here:
https://github.com/vterron/lemon/blob/d60576bec2ad5d1d5043bcb3111dff1fcb58a8d6/methods.py#L536-L573

There's definitely room for a lot of improvement, but it worked for what we
needed.

-- Víctor

**Comment by digglife** [comment]
Not a user of this project, but the method you fix the problem helps me a lot. Thanks you @vterron !

**Comment by slanciano** [comment]
@vterron THANK YOU ! Like @digglife I am not a LEMON user but you helped me to fix my NotImplementedError, thanks 👍 :-)
