### ISSUE TITLE
Issues with photometry when using a file with coordinates of selected stars in the field

### ISSUE THREAD

**Issue by Marioyarce** [vterron/lemon#113]
Hello,

I'm using 0.3-48 version of lemon in Ubuntu 18.04. Given that, there are more than 3000 stars in my images I want to use only selected stars for photometry and correspondingly differential photometry. For that purpose I selected stars in the mosaic image and with the command rimcursor of iraf I create a list of coordinates for these selected stars. When I use this file in LEMON with --coordinates=coord.lis
The output file photometry.LEMONdB I obtain doesn't contain all the stars, nor all images.

My questions are:
-Am I doing this correctly by selecting stars in the mosaic image?
-Can I take the coordinates of the selected stars directly in LEMON and if so, how?
-Is there a minimum number of stars LEMON requieres for differential photometry?

Thanks for your help
Maria Laura

**Comment by vterron** [comment]
Thanks for reaching out!

> -Am I doing this correctly by selecting stars in the mosaic image?

Based on your description yes, it sounds like you're doing it correctly: the `--cordinates` flag takes the path to a file with one row per astronomical object and two coordinates per line: right ascension and declination. The `photometry` command will then look up each of these stars in the mosaic image (to compute, in essence, its instrumental magnitude) and in all of the images on which you're doing photometry. So for example your coordinates  file would look like [this file](https://github.com/vterron/lemon/blob/master/test/integration/WASP10b-coordinates.txt). Is this how it looks like?

> -Can I take the coordinates of the selected stars directly in LEMON and if so, how?

Not sure what you mean, but once you have a `.LEMONdB` database with your light curves you can select any star in the finding chart and go to its page. There you can see the right ascension and declination on the right-hand panel [[example](https://github.com/vterron/lemon/blob/master/Doc/user/images/gui/star-details.png)]. Is this what you meant?

> -Is there a minimum number of stars LEMON requieres for differential photometry?

By default you need at least 8 comparison stars to be able to compute a light curve; see [flag `--minimum-stars`](https://github.com/vterron/lemon/blob/8b2157539353ca68aa2d3e65790062ffcb2cb184/diffphot.py#L881). You also need by default at least 10 FITS images on which the star was visible; that's [flag `--minimum-images`](https://github.com/vterron/lemon/blob/8b2157539353ca68aa2d3e65790062ffcb2cb184/diffphot.py#L855).

A suggestion: run `lemon diffphot` with `-vvv` and save the output to a text file. For example:

```
lemon diffphot -vvv WASP10b-photometry.LEMONdB WASP10b-curves.LEMONdB | tee log.txt
```
You could then upload `log.txt` somewhere and paste the link here and I can take a look.
