### ISSUE TITLE
mosaic — include the type of combination as a keyword

### ISSUE THREAD

**Issue by javierblasco** [vterron/lemon#45]
Hi, 

I'd love to have the type of combination as a separate keyword in this routine, so that I can select median or mean at my convenience. The [corresponding keyword](http://montage-wrapper.readthedocs.org/en/v0.9.5/_generated/montage_wrapper.wrappers.mosaic.html#montage_wrapper.wrappers.mosaic) in mosaic_wrapper is "combine". 

Thanks!
javierblasco

**Comment by vterron** [comment]
Done in bc2cae5. Thanks for the suggestion!
