### ISSUE TITLE
Add PyRAF to the installation instructions

### ISSUE THREAD

**Issue by javierblasco** [vterron/lemon#47]
Hi Victor, 
I think there used to be in the installation instructions a reference to installing pyraf. Would be good to put it there again?

Javi

**Comment by vterron** [comment]
PyRAF is [one of the modules listed](https://github.com/vterron/lemon/blob/b309e895/requirements.txt#L14) listed in the in `requirements.txt` file, so it will be installed when you run `pip install -r requirements.txt`. The installation via `pip` is a recent addition (~2013) and has considerably simplified the process.

**Comment by javierblasco** [comment]
Yes, it seems the problem was the one on issue 48 (https://github.com/vterron/lemon/issues/48). The requirements install failed and I hadn't noticed, so it never reached that far. Thanks!
