### ISSUE TITLE
required version of distribute (>=0.6.28) is not available

### ISSUE THREAD

**Issue by javierblasco** [vterron/lemon#48]
while installing the requirements I stumbled upon this. It seems there is some "hidden dependency" here, maybe you want to take it into account. 

Javi

>Downloading/unpacking matplotlib>=1.2.1 (from -r requirements.txt (line 11))
>  Running setup.py egg_info for package matplotlib
>  The required version of distribute (>=0.6.28) is not available,
>  and can't be installed while this script is running. Please
>  install a more recent version first, using
>    'easy_install -U distribute'.
> 
>   (Currently using distribute 0.6.24dev-r0 (/usr/lib/python2.7/dist-packages))
>    Complete output from command python setup.py egg_info:
>    The required version of distribute (>=0.6.28) is not available,
>
> and can't be installed while this script is running. Please
>
> install a more recent version first, using
> 'easy_install -U distribute'.

**Comment by vterron** [comment]
That's a very good idea, yes. Even if the error message clearly explains how to get a more recent version of `distribute`, it should be included in the installation instructions — especially if, as the README file says, they are the steps needed on a fresh Debian 7 system. Thanks for the suggestion!

Done in c70ad9d.
