### ISSUE TITLE
Include cbox as a parameter for lemon photometry

### ISSUE THREAD

**Issue by javierblasco** [vterron/lemon#50]
Hi Víctor, 

I know you are very much interested in doing photometry exactly in the same coordinates for long periods of time, and that is why you have assigned cbox=0 in the qphot routines. If your filter has very little distortions and your astrometry is very accurate, this will work very well, but I have found that for my own data this is leading to errors in the centre of the standard stars. A possible solution is to put it as an optional parameter in the arguments we parse. A second option would be to include a "-o" option, much in the way you did for astrometry. 

Thanks, 
Javier

**Comment by vterron** [comment]
Done in 5d307d3. This was a very good idea! Thanks!
