### ISSUE TITLE
pygobject

### ISSUE THREAD

**Issue by sengle01** [vterron/lemon#52]
Hello,

Our Linux cluster was recently upgraded to Ubuntu 14.04. I'm not sure if that's the issue (it could be a recent change to lemon) but ever since, I get an error from juicer about pygobject not being installed. I contacted the cluster admin, and he said that gobject is what we currently have installed.

Is there a way to make juicer run with gobject, or do I need to ask that pygobject also be installed?

Best,
Scott

**Comment by sengle01** [comment]
UPDATE

Everything's fine! It turns out the admin was only partially finished with the update to our cluster. Lemon completely works again.

Best,
Scott

**Comment by vterron** [comment]
I'm happy to hear you were able to work it out! My apologies for not having responded earlier. A lot of people started using LEMON at our workplace last week and we are a bit overwhelmed with in-person questions and support requests. I'll do my best to answer all the pending issues as fast as I can.
