### ISSUE TITLE
Reference count error detected:  an attempt was made to deallocate

### ISSUE THREAD

**Issue by EFalco** [vterron/lemon#61]
A new warning, not sure how bad it is:

```
tero 867> lemon diffphot SDSS1004-phot1.LEMONdB SDSS1004-diff1.LEMONdB

Making a copy of the input database... done.
There are 4299 stars in the database

Loading photometric information... done.
44%[===============================> ]**
Light curves for the R filter will now be generated.
Loading photometric information... done.
44%[===============================> ]*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
44%[===============================> ]*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
44%[===============================> ]*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
*** Reference count error detected: 
an attempt was made to deallocate 13 (g) ***
....
```

This keeps repeating over and over.

**Comment by vterron** [comment]
I had never seen a warning like this one — in fact, it seems to be so rare that there is not even much information about it online. From what Travis Oliphant [explained on the [Numpy-discussion] mailing list](https://www.mail-archive.com/numpy-discussion@scipy.org/msg04804.html) in 2007, this seems to be a bug ("It's not really a Python error but a logging.  The code won't let you deallocate the built-ins, but it will tell you that something tried to").

What NumPy version are you running?

    $ python -c "import numpy; print numpy.__version__"

**Comment by EFalco** [comment]
numpy 1.9.1

**Comment by vterron** [comment]
That's a very recent release of NumPy, so I think that if it were merely a problem with that version we would already have seen this — a lot of people, including myself, are running version 1.9.1. We should figure this out, but in the meantime do not worry much about it: this seems to be just a logging error, or at least that is what I understood reading the thread on the NumPy mailing list.

May you please run `diffphot` again, this time with the -vvv flag, and paste the output to [GitHub Gist](https://gist.github.com/) or a similar service? It is probably going to be a lot of text, so you may want to run something like the following command — note the redirection from stderr to stdout:

    lemon diffphot -vvv SDSS1004-phot1.LEMONdB SDSS1004-diff1.LEMONdB 2>&1 | tee diffphot_output
