### ISSUE TITLE
Lemon VM distribution

### ISSUE THREAD

**Issue by dokeeffe** [vterron/lemon#66]
Not an issue, a request. I'd like to have a VM to do data-reduction with Lemon.
Is there anywhere such a VM could be downloaded from?
Thanks,
Derek

**Comment by vterron** [comment]
We don't have any, sorry. We used one for a while a couple of years ago, via [Vagrant](https://www.vagrantup.com/), but it got lost when I left the Institute of Astropysics of Andalusia.

**Comment by dokeeffe** [comment]
No problem actually I created one. Will see if there is anywhere I can publish it for others to use.

**Comment by cdilga** [comment]
@dokeeffe Did you end up publishing the VM?

**Comment by dokeeffe** [comment]
In the end I didnt but I created a docker image here https://github.com/dokeeffe/docker-lemon
It works for me (except the astrometry step as I dont need this step) 
Makes it a lot easier to install
