### ISSUE TITLE
Install Lemon with Ubuntu 15.10

### ISSUE THREAD

**Issue by jorgegocre** [vterron/lemon#67]
Can someone help me with the installation on ubuntu 15.10, please?! 

I am having a lot of rare problems with it.

**Comment by vterron** [comment]
What problems are you having, exactly?

**Comment by jorgegocre** [comment]
I really encourage everybody to install lemon in a Ubuntu 14.04 LTS, the installation is straightforward. I had several problems to install LEMON on other Debian systems.
