### ISSUE TITLE
Problem with montage

### ISSUE THREAD

**Issue by sameerprl** [vterron/lemon#71]
>> Making sure the 2 input paths are FITS images...
>> 100%[======================================================================>]
INFO: Listing raw frames [montage_wrapper.wrappers]
INFO: Computing optimal header [montage_wrapper.wrappers]
INFO: Projecting raw frames [montage_wrapper.wrappers]
Traceback (most recent call last):
  File "/home/sameer/lemon/lemon", line 135, in <module>
    module.main(args)
  File "/home/sameer/lemon/mosaic.py", line 304, in main
    montage.mosaic(input_dir, output_dir, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/montage_wrapper/wrappers.py", line 552, in mosaic
    raw_dir=raw_dir, mpi=mpi, n_proc=n_proc, exact=exact_size)
  File "/usr/local/lib/python2.7/dist-packages/montage_wrapper/commands.py", line 1833, in mProjExec
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
INFO: Deleting work directory /tmp/montage_mosaic_tmpEKt4ma_LEMON_10535_mosaic_input_8IJ9rX [montage_wrapper.wrappers]

**Comment by sameerprl** [comment]
lemon mosaic --cores=1 *.fits mosaic.fits... resolved it!

**Comment by vterron** [comment]
It is very unlikely that `--cores=1` fixed it. Did you change anything in your Montage instalation? The `OSError: [Errno 2] No such file or directory` error seems to indicate that the binary wasn't been found.

**Comment by sameerprl** [comment]
I had tested with uncommenting and commenting the two lines in Makeflie.linux which you had mentioned in the installation procedure, and neither worked

**Comment by sameerprl** [comment]
I didn't make any change in Montage installation

**Comment by vterron** [comment]
That's strange. I guess we'll never know, but glad to hear it's working now.
