### ISSUE TITLE
issue with filter not being a string or buffer

### ISSUE THREAD

**Issue by sameerprl** [vterron/lemon#72]
I have changed the keywords.py according to the header, even then the following error :

sameer@sameer-HP-406-G1-MT:~/Desktop/1HOpt/tester$ lemon photometry --cores=1 mosaic.fits R*.fits test.LEMONdB
>> Examining the headers of the 2 FITS files given as input...
>> 0%[>                                                                        ]Traceback (most recent call last):
  File "/home/sameer/lemon/lemon", line 135, in <module>
    module.main(args)
  File "/home/sameer/lemon/photometry.py", line 688, in main
    pfilter = img.pfilter(options.filterk)
  File "/home/sameer/lemon/fitsimage.py", line 508, in pfilter
    return passband.Passband(pfilter_str)
  File "/home/sameer/lemon/passband.py", line 409, in __init__
    name = re.sub('[\s\-_\(\)]', '', filter_name)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by sameerprl** [comment]
resolved !

**Comment by vterron** [comment]
Could you please explain what the problem was? It could help us improve the code / error message.

**Comment by sameerprl** [comment]
our filters are identified by numerals, so I had modified the header using modhead and replaced numbers with alphabets using a small bash script that I had written
