### ISSUE TITLE
FAIL: test_qphot_run_proper_motions (test_qphot.QPhotTest)

### ISSUE THREAD

**Issue by jorgegocre** [vterron/lemon#75]
iemath@iemath-All-Series:~/lemon$ ./run_tests.py
	test_best (test_diffphot.StarSetTest) ... ok
	test_best_fraction_out_of_range (test_diffphot.StarSetTest) ... ok
	test_best_less_than_three_stars (test_diffphot.StarSetTest) ... ok
	test_best_number_of_stars_out_of_range (test_diffphot.StarSetTest) ... ok
	test_broeg_weights_fewer_than_two_images (test_diffphot.StarSetTest) ... ok
	test_broeg_weights_fewer_than_two_stars (test_diffphot.StarSetTest) ... ok
	test_broeg_weights_one_iteration (test_diffphot.StarSetTest) ... ok
	test_broeg_weights_two_iterations (test_diffphot.StarSetTest) ... ok
	test_broeg_weights_two_stars (test_diffphot.StarSetTest) ... ok
	test_delitem (test_diffphot.StarSetTest) ... ok
	test_flux_proportional_weights (test_diffphot.StarSetTest) ... ok
	test_init_and_get (test_diffphot.StarSetTest) ... ok
	test_light_curve_basic_case (test_diffphot.StarSetTest) ... ok
	test_light_curve_errors (test_diffphot.StarSetTest) ... ok
	test_light_curve_exclude_index (test_diffphot.StarSetTest) ... ok
	test_light_curve_more_complex_case (test_diffphot.StarSetTest) ... ok
	test_star_ids_len_and_nimages (test_diffphot.StarSetTest) ... ok
	test_worst (test_diffphot.StarSetTest) ... ok
	test_worst_fraction_out_of_range (test_diffphot.StarSetTest) ... ok
	test_worst_less_than_three_stars (test_diffphot.StarSetTest) ... ok
	test_absolute_percent_change (test_diffphot.WeightsTest) ... ok
	test_inversely_proportional (test_diffphot.WeightsTest) ... ok
	test_new (test_diffphot.WeightsTest) ... ok
	test_normalize (test_diffphot.WeightsTest) ... ok
	test_random (test_diffphot.WeightsTest) ... ok
	test_rescale (test_diffphot.WeightsTest) ... ok
	test_total (test_diffphot.WeightsTest) ... ok
	test_difference_error (test_snr.SNRTest) ... ok
	test_difference_snr (test_snr.SNRTest) ... ok
	test_error_to_snr (test_snr.SNRTest) ... ok
	test_snr_to_error (test_snr.SNRTest) ... ok
	test_unweighted_mean_error (test_snr.SNRTest) ... ok
	test_unweighted_mean_snr (test_snr.SNRTest) ... ok
	test_weighted_mean_error (test_snr.SNRTest) ... ok
	test_weighted_mean_snr (test_snr.SNRTest) ... ok
	test_get_coords_file (test_qphot.QPhotTest) ... ok
	test_qphot_run (test_qphot.QPhotTest) ... ok
	test_qphot_run_nonzero_cbox (test_qphot.QPhotTest) ... ok
	test_qphot_run_proper_motions (test_qphot.QPhotTest) ... FAIL

	======================================================================
	FAIL: test_qphot_run_proper_motions (test_qphot.QPhotTest)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/home/iemath/lemon/test/test_qphot.py", line 300, in test_qphot_run_proper_motions
	    f(dec, expected_coordinates.dec, delta = 1e-7) # delta = 0.00036 arsec
	AssertionError: array(4.674883867122548) != 4.6749296929182735 within 1e-07 delta

	----------------------------------------------------------------------
	Ran 39 tests in 31.565s

	FAILED (failures=1)

**Comment by vterron** [comment]
This looks a lot like the problem in #57, because of the occasional (and very small) difference in some of the values computed by `qphot`. I would not worry about this at all: the photometry is working well, except that after a few (and basically negligible) decimal places the returned values differ on 32-bit and 64-bit platforms. As mentioned in #59, this will no longer be an issue once we replace IRAF with [photutils](https://photutils.readthedocs.org).
