### ISSUE TITLE
lemon photometry performing photometry on saturated stars

### ISSUE THREAD

**Issue by StuartLittlefair** [vterron/lemon#77]
We have a series of single exposure images (NCOADDS=1) and are running the photometry code with the `--maximum=43000` option to reflect the full well depth of our CCD. We have several images in which the stars are saturated and yet these stars still have photometric measurements in the lightcurves for these images. The output is consistent with this - i.e for a file in which we know this star to be saturated, we see

```
2016-03-03 13:59:10,033 - root - DEBUG - /tmp/mosaic_120_wOul_A.fits_satur_mask_9223372036854775807_ADUS_Myb3Nd.fits: xcenter = 746.81600000
2016-03-03 13:59:10,033 - root - DEBUG - /tmp/mosaic_120_wOul_A.fits_satur_mask_9223372036854775807_ADUS_Myb3Nd.fits: ycenter = 710.11600000
2016-03-03 13:59:10,033 - root - DEBUG - /tmp/mosaic_120_wOul_A.fits_satur_mask_9223372036854775807_ADUS_Myb3Nd.fits: mag = None ('INDEF')
```

**Comment by vterron** [comment]
In this case, `mag = None ('INDEF')` means that the star is too faint to determine an instrumental magnitude. In the `photometry` module INDEF photometric measurements have a magnitude of None, and those with at least one saturated pixel in the aperture have a magnitude of infinity. But in both cases these values are not even stored in the database, as they are useless for our purposes.

Could you please upload a few of your FITS images (say twenty) somewhere, as a minimal working example, and post the URL here / send it to me via email? I would like to take a look at this as soon as I can resume the development of the pipeline.

**Comment by StuartLittlefair** [comment]
Thank you for clearing that up.

I've uploaded ~100 images which show the issue, as well as the diffphot database and a log showing the verbose output of the photometry command. Star 152 in the database is one which I think shows data when the star is clearly saturated, for example in frame r0267271s.fits
