### ISSUE TITLE
Prevent discarding images with same header and same time info

### ISSUE THREAD

**Issue by sameeresque** [vterron/lemon#79]
Please make a provision to perform photometry on images with same header and same time info, this is helpful when analysing images generated as cubes , as all the images contain the same header information.

**Comment by vterron** [comment]
Please don't open issues and close them immediately afterwards :D

For the record, it would be impossible to add this feature: the entire algorithm for differential photometry is based on the assumption that there is only one measurement for each point in time and photometric filter. Even if we could work around this, how would we later on generate the light curves if there are multiple points? My recommendation is that you combine all the images in the FITS cube, obtaining a single image and at the same time maximizing the signal-to-noise ratio.
