### ISSUE TITLE
Cousin filters addition to filters list

### ISSUE THREAD

**Issue by paramoreta** [vterron/lemon#81]
Dear PyLord,

I'm running the rename.py routine and it has failed to recognize the Cousin filters system of my images.
The header's filter keyword naming the astronomers chose is kind of... loose to say the least so, no surprise:

`INSFLNAM= 'Cous R    '`

Could this filter be added to the list, please?
I'd bet any suitable combination of Cousin and the proper letter is possible in this marvelous and proper-naming-rules-free world of astronomy so maybe it is interesting to add a couple of variants (assuming the blank space between family and letter is relevant) such as:

CousR
Cous R
CousinR
Cousin R

Btw, the script returns:

```
Traceback (most recent call last):
  File "/mnt/DATA/pablo/work/routines/repipy/rename.py", line 349, in <module>
    main()
  File "/mnt/DATA/pablo/work/routines/repipy/rename.py", line 346, in main
    fits_dict = rename(args)
  File "/mnt/DATA/pablo/work/routines/repipy/rename.py", line 219, in rename
    object_filter = im.filter.__str__()
  File "/mnt/DATA/pablo/work/routines/repipy/filter.py", line 35, in __str__
    filter_alias =  passband.Passband( filtersys + filtername).__str__()
  File "/mnt/DATA/pablo/work/routines/lemon/passband.py", line 424, in __init__
    letter = self._parse_name(name, system)
  File "/mnt/DATA/pablo/work/routines/lemon/passband.py", line 331, in _parse_name
    raise NonRecognizedPassband(name)
lemon.passband.NonRecognizedPassband: cannot identify the photometric system of filter 'CousR'. If this is a legitimate filter name, and you think LEMON should be able to recognize it, please let us know at [http://github.com/vterron/lemon/issues]. In the meantime, you can define your own filters in the /home/username/.lemonrc file, as options of the [custom_filters] section
```

I have checked my /home/username/.lemonrc file but it is empty.
The next comment "as options of the [custom_filters] section" did not help to clarify. I don't know what that section is, nor how the filter definition must look like so I did not dare to try. 

Any help will be greatly appreciated!

Thanks!

**Comment by vterron** [comment]
The error message is not helpful if you don't already know what's going on, I agree. Thanks for pointing this out — I'll fix this. A proper explanation on how to use `[custom_filters]` can be found [on this comment](https://github.com/vterron/lemon/issues/14#issuecomment-43504285), back from when the feature was added. In your case, I think you would like something like this:

    [custom_filters]
    Cous V = Cousins V
    Cous R = Cousins R
    Cous V = Cousins I
    
This should do while I add `Cous R` and similar abominations to the list of filters that are automatically recognized.

**Comment by paramoreta** [comment]
Most brilliant. These definitions should do for now indeed.
Thanks for the info and help!

**Comment by vterron** [comment]
Error message improved in 6b9e466.

**Comment by vterron** [comment]
Done in 64d6d51. Your filters should now work without the need of a /.lemonrc file.

**Comment by vterron** [comment]
Error message improved in 6b9e466.
