### ISSUE TITLE
Temp Folder Location

### ISSUE THREAD

**Issue by sengle01** [vterron/lemon#87]
Hello,

Here's what I'm assuming would be an easy one, but in looking over some of the routines, I didn't readily see an option for it. How would I go about changing the location of the temp folder used by Lemon?

Best,
Scott

**Comment by vterron** [comment]
The location of the temporary folders is determined in Python by a global variable: [tempfile.tempdir](https://docs.python.org/2/library/tempfile.html#tempfile.tempdir). LEMON does not set it, so all the functions of the `tempfile` module search a standard list of directories and set the temporary directory to the first one in which the user can create files. The list is:

1. The directory named by the **TMPDIR** environment variable.
2. The directory named by the **TEMP** environment variable.
3. The directory named by the **TMP** environment variable.
4. A platform-specific location:
    - On RiscOS, the directory named by the **Wimp$ScrapDir** environment variable.
    - On Windows, the directories `C:\TEMP`, `C:\TMP`, `\TEMP`, and `\TMP`, in that order.
    - On all other platforms, the directories `/tmp`, `/var/tmp`, and `/usr/tmp`, in that order.
5. As a last resort, the current working directory.

Thus, you could add something like this line to your `.bashrc` file:

`export TMPDIR=/data/tmp/`

**Comment by sengle01** [comment]
Oh perfect. Thank you so much for the quick response. 

Best,
Scott
