### ISSUE TITLE
Installation run_tests.py , nr 46

### ISSUE THREAD

**Issue by stpstp** [vterron/lemon#92]
Hello,
I recently installed lemon, and ran the test scripts.  All but the last test were OK.
The last test produced an error (see below), with  a different result starting in the 4th decimal.  0.00036 arcsec error is not worrying at all for my projects.

Given the fact that the other 45 tests finished OK, it does not appear to be due to an error in the installation, any ideas? 

thanks in advance
Saskia

```
here's the output from the last test:
FAIL: test_qphot_run_proper_motions (test_qphot.QPhotTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lhome/stp/src/python/mrs/lemon/test/test_qphot.py", line 300, in test_qphot_run_proper_motions
    f(dec, expected_coordinates.dec, delta = 1e-7) # delta = 0.00036 arsec
AssertionError: array(4.674883867122548) != 4.6749296929182735 within 1e-07 delta
```

**Comment by vterron** [comment]
This is the same problem we saw in #75. The TL;DR is that there seems to be an occasional and negligible difference between the values that `qphot` computes on 32-bit vs 64-bit platforms. As mentioned in #59 , this will no longer be an issue once we replace IRAF with [photutils](https://photutils.readthedocs.org).
