### ISSUE TITLE
astrometry.net not solving

### ISSUE THREAD

**Issue by sengle01** [vterron/lemon#97]
Hello,

Recently astrometry.net has been having very little success solving any of my images. It's been happening for the past couple months. 

However, if I just use solve-field, it works successfully. I'm attaching a sample image, along with my lemon astrometry file and the astrometry config file. The commands that I try:

```
solve-field a180112234s.fits --dir astrom --no-plots --overwrite --radius 0.2 --config /home/users/sengle01/astrometry_net/astrometry.cfg -u arcsecperpix -L 0.5 -H 0.7
```

which works. Here are the results:

```
  log-odds ratio 26.6871 (3.89097e+11), 11 match, 0 conflict, 43 distractors, 30 index.
  RA,Dec = (175.566,26.7703), pixel scale 0.570657 arcsec/pix.
  Hit/miss:   Hit/miss: ---+-------+--------+---+---+-+--------+------+-+-+--+(best)---++++
Field 1: solved with index index-4203-27.fits.
Field 1 solved: writing to file astrom/a180112234s.solved to indicate this.
Field: a180112234s.fits
Field center: (RA,Dec) = (175.566507, 26.770144) deg.
Field center: (RA H:M:S, Dec D:M:S) = (11:42:15.962, +26:46:12.519).
Field size: 9.75012 x 9.75096 arcminutes
Field rotation angle: up is 92.4105 degrees E of N
Field parity: neg
Creating new FITS file "astrom/a180112234s.new"...
```

But then running

```
lemon astrometry -v --rak CRVAL1 --deck CRVAL2 a180112234s.fits astrom/
```

constantly fails to solve the image, and this happens for a whole bunch of images taken recently. And I can see that it is searching index-4203-27, which is the one that works for solve-field. It's just not working through lemon.

The one warning I get is:

```
RequestsDependencyWarning: urllib3 (1.21.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
```

Is it possible that urllib3 or chardet are preventing it from working? I would imagine not, because this is something that primarily happens with images taken in the past few months. Images taken before that solve much more consistently. 

Any advice you can give would be much appreciated.

Best,
Scott
[astrometry_net.zip](https://github.com/vterron/lemon/files/1641489/astrometry_net.zip)

**Comment by vterron** [comment]
Hi Scott,

I just tried the same command as you and and the image solve correctly:

```
$ lemon astrometry -v --rak CRVAL1 --deck CRVAL2 a180112234s.fits astrom/
>> The output directory 'astrom/' did not exist, so it had to be created.
>> Using a local build of Astrometry.net.
>> Doing astrometry on the 1 paths given as input.
Reading input file 1 of 1: "a180112234s.fits"...
Found an existing WCS header, will try to verify it.
Extracting sources...
[...]
  log-odds ratio 26.6871 (3.89097e+11), 11 match, 0 conflict, 43 distractors, 30 index.
  RA,Dec = (175.566,26.7703), pixel scale 0.570657 arcsec/pix.
  Hit/miss:   Hit/miss: ---+-------+--------+---+---+-+--------+------+-+-+--+(best)---++++
Field 1: solved with index index-4203-27.fits.
Field 1 solved: writing to file /tmp/a180112234s_XBNVPk_astrometry.net/a180112234s.solved to indicate this.
Field: a180112234s.fits
Field center: (RA,Dec) = (175.6, 26.77) deg.
Field center: (RA H:M:S, Dec D:M:S) = (11:42:15.962, +26:46:12.519).
Field size: 9.75012 x 9.75096 arcminutes
Field rotation angle: up is 92.4105 degrees E of N
Creating new FITS file "/tmp/a180112234s_astrometry_IfZXSq.fits"...

>> 100%[======================================================================>]
>> You're done ^_^
2018-01-30 22:11:27,478 - root - INFO - LEMON Git revision: v0.3-36-g67eb459-dirty
```

**Comment by vterron** [comment]
Could you paste here the output of the following two commands, run inside the lemon directory?

```
$ cut -d ">" -f 1 requirements.txt pre-requirements.txt | grep -v "#" | grep -v '^$' > lemon-packages.txt
$ pip freeze | grep -f lemon-packages.txt
```

It should print something like:

```
APLpy==0.9.13
astropy==1.0.2
d2to1==0.2.11
matplotlib==1.4.1
mock==1.0.1
montage-wrapper==0.9.8
pyfits==3.2
pyraf==2.1.7
requests==2.5.1
scipy==0.14.0
subprocess32==3.2.6
uncertainties==2.4.6.1
unittest2==0.5.1
```

This will allow me to install the same package versions as you in a virtualenv to try to reproduce the problem.

**Comment by sengle01** [comment]
Víctor,

Great hearing from you. I ran the commands, but didn't get the version numbers except for 'requests'.
[lemon-packages.txt](https://github.com/vterron/lemon/files/1684194/lemon-packages.txt)

The second command gave the requests version:

requests==2.9.1

Did I possibly run the commands wrong?

Best,
Scott

**Comment by sengle01** [comment]
I manually hunted down the versions. Our Linux cluster was recently re-built, and I now see that some of the previously installed modules didn't get re-installed. It's very possible that's the cause, but I will contact the admin about installing the missing modules...

APLpy == not installed
astropy == u'1.2.1'
d2to1 == '0.2.12.post1'
matplotlib == '2.0.2'
mock == not installed
montage-wrapper == not installed
pyfits == '3.4'
pyraf == '2.1.14'
requests == '2.18.1'
scipy == '0.19.1'
subprocess32 == oddly enough, it tells me there is no version attribute for this one
uncertainties == not installed
unittest2 == not installed

**Comment by sengle01** [comment]
OK. A very quick update. Our admin was still awake and installed everything. The recent images are still failing to solve for some reason. But here are the versions.

APLpy == u'1.1.1'
 astropy == u'1.2.1'
 d2to1 == '0.2.12.post1'
 matplotlib == '2.0.2'
 mock == '2.0.0'
 montage-wrapper == u'0.9.9'
 pyfits == '3.4'
 pyraf == '2.1.14'
 requests == '2.18.1'
 scipy == '0.19.1'
 subprocess32 == oddly enough, it tells me there is no version attribute for this one
 uncertainties == '3.0.1'
 unittest2 == '1.1.0'

**Comment by vterron** [comment]
Thanks, I'll try to install those versions for all the packages and reproduce the problem.

In the meantime, could you confirm `subprocess32` is installed?

Also, if you run `run_tests.py`, do all tests pass?
