### ISSUE TITLE
./run_tests.py failed

### ISSUE THREAD

**Issue by hlabathems** [vterron/lemon#98]
I get the following error when running ./run_tests.py

```
Traceback (most recent call last):
  File "/Users/michaelhlabathe/lemon/test/test_database.py", line 2498, in test_star_closest_to_world_coords
    self.assertEqual(distance, 47.939281840122732)
AssertionError: 47.93928184012274 != 47.93928184012273

----------------------------------------------------------------------
Ran 48 tests in 61.142s

FAILED (failures=1)
```

**Comment by vterron** [comment]
This was a bug in the unit test: it should use [assertAlmostEqual()](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertAlmostEqual) to compare the two floating point numbers, in the same way we do just a few lines above for the other distances. Thanks for reporting this!
